### ISSUE TITLE
是不是少文件了....

### ISSUE THREAD

**Issue by jaredwangcode** [lgx0955/BalaBala#1]
Error:(20, 41) 错误: 找不到符号
符号:   变量 menu_main
位置: 类 menu
Error:(32, 23) 错误: 找不到符号
符号:   变量 action_settings
位置: 类 id
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
R.menu.menu_main R.id.action_settings

**Comment by lgx0955** [comment]
新版已修复
